# Generated by Django 5.2.5 on 2025-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
                ("price", models.FloatField()),
                ("instock", models.BooleanField()),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updateat", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
