# Generated by Django 5.2.5 on 2025-08-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="createdat",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="updateat",
            new_name="update_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="instock",
        ),
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
    ]
