# Generated by Django 5.2.5 on 2025-08-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_createdat_product_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
